---
- name: "Check: {{ dhcp_network.value.address }} network is exist"
  routeros_command:
    commands: /ip dhcp-server network print address="{{ dhcp_network.value.address }}"
  register: network_status

- name: "Add {{ dhcp_network.value.address }} dhcp network"
  routeros_command:
    commands: >
      /ip dhcp-server network add
      address="{{ dhcp_network.value.address }}"
      comment="{{ dhcp_network.value.comment }}"
      dns-server="{{ dhcp_network.value.dns_server }}"
      gateway="{{ dhcp_network.value.gateway }}"
      domain="{{ dhcp_network.value.domain | default('') }}"
      next-server="{{ dhcp_network.value.next_server | default('') }}"
      boot-file-name="{{ dhcp_network.value.boot_file_name | default('') }}"
      {{ dhcp_network.value.other_params | default('') }}
  when: '"0" not in network_status.stdout[0]'

- name: "Update {{ dhcp_network.value.address }} dhcp server"
  routeros_command:
    commands: >
      /ip dhcp-server network set [ find address="{{ dhcp_network.value.address }}"]
      comment="{{ dhcp_network.value.comment }}"
      dns-server="{{ dhcp_network.value.dns_server }}"
      gateway="{{ dhcp_network.value.gateway }}"
      domain="{{ dhcp_network.value.domain | default('') }}"
      next-server="{{ dhcp_network.value.next_server | default('') }}"
      boot-file-name="{{ dhcp_network.value.boot_file_name | default('') }}"
      {{ dhcp_network.value.other_params | default('') }}
  when: '"0" in network_status.stdout[0]'