---
- name: "[DEBUG] RouterOs Commands"
  debug:
    msg:
    - /ip dhcp-client print where interface="{{ dhcp_client['interface'] }}"
    - >
      /ip dhcp-client add
        interface="{{ dhcp_client['interface'] }}"
        comment="{{ dhcp_client['comment'] | default('') }}"
        {% if dhcp_client['other_params'] is defined %}{{ dhcp_client['other_params'] }}{% endif %}
    - >
      /ip dhcp-client set [ find interface="{{ dhcp_client['interface'] }}"]
        comment="{{ dhcp_client['comment'] | default('') }}"
        {% if dhcp_client['other_params'] is defined %}{{ dhcp_client['other_params'] }}{% endif %}
  when: input_role_debug == true

- name: "Check: {{ dhcp_client['interface'] }} dhcp client is exist"
  routeros_command:
    commands: /ip dhcp-client print where interface="{{ dhcp_client['interface'] }}"
  register: dhcp_client_status

- name: "[DEBUG] Check: {{ dhcp_client['interface'] }} dhcp client is exist output"
  debug:
    msg: "{{ dhcp_client_status.stdout_lines }}"
  when:
    - input_role_debug == true
    - dhcp_client_status.stdout_lines is defined

- name: Add {{ dhcp_client['interface'] }} dhcp client
  routeros_command:
    commands: >
      /ip dhcp-client add
        interface="{{ dhcp_client['interface'] }}"
        comment="{{ dhcp_client['comment'] | default('') }}"
        {% if dhcp_client['other_params'] is defined %}{{ dhcp_client['other_params'] }}{% endif %}
  when: '" 0 " not in dhcp_client_status.stdout[0]'
  register: add_dhcp_client_status

- name: "[DEBUG] Add {{ dhcp_client['interface'] }} dhcp client output"
  debug:
    msg: "{{ add_dhcp_client_status.stdout_lines }}"
  when:
    - input_role_debug == true
    - add_dhcp_client_status.stdout_lines is defined

- name: "Update {{ dhcp_client['interface'] }} dhcp client"
  routeros_command:
    commands: >
      /ip dhcp-client set [ find interface="{{ dhcp_client['interface'] }}"]
        comment="{{ dhcp_client['comment'] | default('') }}"
        {% if dhcp_client['other_params'] is defined %}{{ dhcp_client['other_params'] }}{% endif %}
  when: '" 0 " in dhcp_client_status.stdout[0]'
  register: update_dhcp_client_status

- name: "[DEBUG] Update {{ dhcp_client['interface'] }} dhcp client output"
  debug:
    msg: "{{ update_dhcp_client_status.stdout_lines }}"
  when:
    - input_role_debug == true
    - update_dhcp_client_status.stdout_lines is defined