---
- name: "Check: {{ dhcp_client.interface }} dhcp client is exist"
  routeros_command:
    commands: /ip dhcp-client print where interface="{{ dhcp_client.interface }}"
  register: dhcp_client_status

- name: Add {{ dhcp_client.interface }} dhcp client
  routeros_command:
    commands: >
      /ip dhcp-client add 
      interface="{{ dhcp_client.interface }}"
      comment="{{ dhcp_client.comment | default('') }}" 
      {{ dhcp_client.other_params | default('') }}
  when: '" 0 " not in dhcp_client_status.stdout[0]'

- name: Update {{ dhcp_client.interface }} dhcp client
  routeros_command:
    commands: >
      /ip dhcp-client set [ find interface="{{ dhcp_client.interface }}"] 
      comment="{{ dhcp_client.comment | default('') }}" 
      {{ dhcp_client.other_params | default('') }}
  when: '" 0 " in dhcp_client_status.stdout[0]'