input_role_debug: false

input_role_wireless_interfaces:
  wlan1:
    name: WiFi-LAN-01
    comment: "SSID: {{ input_role_wireless_security_profiles.UsersWifiNetwork.name }}"
    ssid: "{{ input_role_wireless_security_profiles.UsersWifiNetwork.name }}"
    security_profile: "{{ input_role_wireless_security_profiles.UsersWifiNetwork.name }}"
    band: "2ghz-b/g/n"
    channel-width: "20/40mhz-XX"
    address: "10.0.0.4/24"
    network: "10.0.0.0"
    graphing:
      allow-address: 0.0.0.0/0
      store-on-disk: "no"
  wlan2:
    name: WiFi-LAN-02
    ssid: "{{ input_role_wireless_security_profiles.UsersWifiNetwork.name }}"
    band: "5ghz-a/n/ac"
    channel-width: "20/40/80mhz-XXXX"
    security-profile: "{{ input_role_wireless_security_profiles.UsersWifiNetwork.name }}"
    address: "10.0.0.5/24"
    network: "10.0.0.0"
    graphing:
      allow-address: 0.0.0.0/0
      store-on-disk: "no"

input_role_wireless_security_profiles:
  default: # if one element in dictionary
  UsersWifiNetwork:
    name: "Users Wifi Network"
    password: "PaSSw0rd!"