---
- name: "Check: {{ pool.value.name }} pool is exist"
  routeros_command:
    commands: /ip pool print from="{{ pool.value.name }}"
  register: pool_status

- name: Add {{ pool.value.name }} pool
  routeros_command:
    commands: >
      /ip pool add 
      name="{{ pool.value.name }}"
      comment="{{ pool.value.comment | default('') }}" 
      ranges="{{ pool.value.ranges }}"
      {{ pool.value.other_params | default('') }}
  when: '"no such item" in pool_status.stdout[0]'

- name: Update {{ pool.value.name }} pool
  routeros_command:
    commands: >
      /ip pool set [ find name="{{ pool.value.name }}"] 
      comment="{{ pool.value.comment | default('') }}" 
      ranges="{{ pool.value.ranges }}"
      {{ pool.value.other_params | default('') }}
  when: '"no such item" not in pool_status.stdout[0]'