---
- name: "Check: {{ interface_list.value.name }} interface list is exist"
  routeros_command:
    commands: /interface list print from={{ interface_list.value.name }}
  register: list_status

- name: "Add interface list {{ interface_list.value.name }}"
  routeros_command:
    commands: >
      /interface list add
      name={{ interface_list.value.name }}
      comment="{{ interface_list.value.comment | default('') }}"
      {{ interface_list.value.other_params | default('') }}
  when: '"no such item" in list_status.stdout[0]'

- name: "Update interface list {{ interface_list.value.name }}"
  routeros_command:
    commands: >
        /interface list set [find name={{ interface_list.value.name }}]
        name={{ interface_list.value.name }}
        comment="{{ interface_list.value.comment | default('') }}"
        {{ interface_list.value.other_params | default('') }}
  when: '"no such item" not in list_status.stdout[0]'

# Members
- name: Configure members of interface list
  include: configure_list_interface_members.yml
  loop: "{{ interface_list.value.interfaces }}"
  loop_control:
    loop_var: member
  when: interface_list.value.interfaces is defined