---
- name: Add wireless security profile
  routeros_command:
    commands: >
      /interface wireless security-profiles add name={{ security_profile.value.name }}

- name: debug
  debug:
    msg: >
      authentication-types={{ security_profile.value.authentication_types | default(vars_role_wireless_security_profiles.authentication_types) }}

- name: Update wireless security profile
  routeros_command:
    commands:
      - >
        /interface wireless security-profiles set [ find name={{ security_profile.value.name }}]
        mode={{ security_profile.value.mode | default(vars_role_wireless_security_profiles.mode) }}
        wpa-pre-shared-key="{{ security_profile.value.password }}"
        wpa2-pre-shared-key="{{ security_profile.value.password }}"
        authentication-types="{{ security_profile.value.authentication_types | default(vars_role_wireless_security_profiles.authentication_types) }}"
        {{ security_profile.value.other_params | default('') }}
  register: test

- name: test
  debug:
    msg: "{{ test }}"