---
- name: "Check: {{ vlan.value.name }} is vlan exist"
  routeros_command:
    commands: >
        /interface vlan print from="{{ vlan.value.name }}"
  register: vlan_status

- name: "Add VLAN interface {{ vlan.value.name }}"
  routeros_command:
    commands: >
      /interface vlan add
      name={{ vlan.value.name }}
      interface="{{ vlan.value.interface }}"
      vlan-id={{ vlan.value.vlan_id }}
      comment="{{ vlan.value.comment | default('') }}"
      {{ vlan.value.other_params | default('') }}
  when: '"no such item" in vlan_status.stdout[0]'
  
- name: "Update VLAN interface {{  vlan.value.name  }}"
  routeros_command:
    commands: >
      /interface vlan set [find name={{ vlan.value.name }}]
      interface="{{ vlan.value.interface }}"
      vlan-id={{ vlan.value.vlan_id }}
      comment="{{ vlan.value.comment | default('') }}"
      {{ vlan.value.other_params | default('') }}
  when: '"no such item" not in vlan_status.stdout[0]'

### SET IP ADRESS

- name: "Check is set ip address for {{ vlan.value.name }}"
  routeros_command:
    commands: >
      /ip address print where address="{{ vlan.value.address }}" interface={{ vlan.value.name }}
  register: vlan_interface_ip_status
  when:
    - vlan.value.address is defined
    - vlan.value.name is defined
- debug:
    msg: "{{ vlan_interface_ip_status }}"

- name: "Add ip address for {{ vlan.value.name }} - {{ vlan.value.address }}"
  routeros_command:
    commands: >
      /ip address add
      address={{ vlan.value.address }}
      network={{ vlan.value.network }}
      interface={{ vlan.value.name }}
      comment="{{ vlan.value.comment | default('') }}"
  when:
    - vlan.value.address is defined
    - vlan.value.name is defined
    - '" 0 " not in vlan_interface_ip_status.stdout[0]'
  register: testc
- debug:
    msg: "{{ testc }}"

- name: "Update ip address for {{ vlan.value.name }} - {{ vlan.value.address }}"
  routeros_command:
    commands: >
      /ip address set [ find address="{{ vlan.value.address }}"] 
      address={{ vlan.value.address }}
      network={{ vlan.value.network }}
      interface={{ vlan.value.name }}
      comment="{{ vlan.value.comment | default('') }}"
  when:
    - vlan.value.address is defined
    - vlan.value.name is defined
    - '" 0 " in vlan_interface_ip_status.stdout[0]'
  register: testd
- debug:
    msg: "{{ testd }}"

### SET GRAPHING
- name: "Check is set graphing for {{ vlan.value.name }}"
  routeros_command:
    commands: >
      /tool graphing interface print where interface="{{ vlan.value.name }}"
  register:  graphing_interface_status

- name: "Add graphing for {{ vlan.value.name }}"
  routeros_command:
    commands: >
      /tool graphing interface add
      interface={{ vlan.value.name }}
      store-on-disk={{ vlan.value.graphing.store_on_disk }}
      allow-address="{{ vlan.value.graphing.allow_address | default('') }}"
  when:
    - vlan.value.graphing is defined
    - '" 0 " not in graphing_interface_status.stdout[0]'

- name: "Update graphing for {{ vlan.value.name }}"
  routeros_command:
    commands: >
      /tool graphing interface set [ find interface="{{ vlan.value.name }}"] 
      store-on-disk={{ vlan.value.graphing.store_on_disk }}
      allow-address="{{ vlan.value.graphing.allow_address | default('') }}"
  when:
    - vlan.value.graphing is defined
    - '" 0 " in graphing_interface_status.stdout[0]'