---
- name: "Check: {{ security_profile.value.name }} is wireless security profile exist"
  routeros_command:
    commands: >
        /interface wireless security-profiles print from="{{ security_profile.value.name }}"
  register: security_profile_status

- name: Add wireless security profile
  routeros_command:
    commands: >
        /interface wireless security-profiles add
        name={{ security_profile.value.name }}
        authentication-types="{{ security_profile.value.authentication_types | default(vars_role_wireless_security_profiles.authentication_types) }}"
        mode={{ security_profile.value.mode | default(vars_role_wireless_security_profiles.mode) }}
        wpa-pre-shared-key="{{ security_profile.value.password }}"
        wpa2-pre-shared-key="{{ security_profile.value.password }}"
        {{ security_profile.value.other_params | default('') }}
  when: '"no such item" in security_profile_status.stdout[0]'

- name: Update wireless security profile
  routeros_command:
    commands: >
      /interface wireless security-profiles set [ find name={{ security_profile.value.name }}]
      authentication-types="{{ security_profile.value.authentication_types | default(vars_role_wireless_security_profiles.authentication_types) }}"
      mode={{ security_profile.value.mode | default(vars_role_wireless_security_profiles.mode) }}
      wpa-pre-shared-key="{{ security_profile.value.password }}"
      wpa2-pre-shared-key="{{ security_profile.value.password }}"
      {{ security_profile.value.other_params | default('') }}
  when: '"no such item" not in security_profile_status.stdout[0]'