---
- name: "Check: {{ bridge.name }} is brige exist"
  routeros_command:
    commands: /interface bridge print from={{ bridge.name }}
  register: bridge_status

- name: "Add Brigde name {{ bridge.name }}"
  routeros_command:
    commands: >
      /interface bridge add
      name="{{ bridge.name }}"
      comment="{{ bridge.comment }}"
      {{ bridge.other_params | default('') }}
  when: '"no such item" in bridge_status.stdout'

- name: "Update Brigde name {{ bridge.name }}"
  routeros_command:
    commands: >
      /interface bridge set [find name={{ bridge.name }}]
      comment="{{ bridge.comment }}"
      {{ bridge.other_params | default('') }}
  when: '"no such item" not in bridge_status.stdout'

- name: "Add interface {{ item.name }} to {{ bridge.name }} bridge"
  routeros_command:
    commands: >
      /interface bridge port add
      bridge={{ bridge.name }}
      interface={{ item.name }}
      trusted={{ item.trusted }}
  loop: "{{ bridge.interfaces }}"
  when: bridge.interfaces is defined