---
- name: "Check: {{ bridge.value.name }} is brige exist"
  routeros_command:
    commands: /interface bridge print from={{ bridge.value.name }}
  register: bridge_status

- name: "Add Brigde name {{ bridge.value.name }}"
  routeros_command:
    commands: >
      /interface bridge add
      name="{{ bridge.value.name }}"
      comment="{{ bridge.value.comment }}"
      {{ bridge.value.other_params | default('') }}
  when: '"no such item" in bridge_status.stdout[0]'

- name: "Update Brigde name {{ bridge.value.name }}"
  routeros_command:
    commands: >
      /interface bridge set [find name={{ bridge.value.name }}]
      comment="{{ bridge.value.comment }}"
      {{ bridge.value.other_params | default('') }}
  when: '"no such item" not in bridge_status.stdout[0]'

- name: "Add interface to {{ bridge.value.name }} bridge"
  routeros_command:
    commands: >
        /interface bridge port add
        bridge={{ bridge.value.name }}
        interface={{ item.name }}
        trusted={{ item.trusted }}
  loop: "{{ bridge.value.interfaces }}"
  when: bridge.value.interfaces is defined