---
- name: "Update Ethernet interface {{ ethernet.key }}"
  routeros_command:
    commands: >
      /interface ethernet set [find default-name={{ ethernet.key }}]
      name={{ ethernet.value.name }}
      comment="{{ ethernet.value.comment | default('') }}"
      {{ ethernet.value.other_params | default('') }}
