---
- name: Configure wireless security profiles
  include: configure_wireless_security_profiles.yml
  loop: "{{ lookup('dict', input_role_wireless_security_profiles) }}"
  loop_control:
    loop_var: security_profile
  when: 
    - input_role_wireless_security_profiles is defined
    - security_profile.key != "default"

- name: Configure wireless interfaces
  include: configure_wireless_interfaces.yml
  loop: "{{ lookup('dict', input_role_wireless_interfaces) }}"
  loop_control:
    loop_var: wireless_interface
  when: 
    - input_role_wireless_interfaces is defined
    - wireless_interface.key != "default"

- name: Configure Ethernet interfaces
  include: configure_ethernet.yml
  loop: "{{ lookup('dict', input_role_ethernet_interfaces) }}"
  loop_control:
    loop_var: ethernet
  when: 
    - input_role_ethernet_interfaces is defined
    - ethernet.key != "default"

- name: Configure bridges
  include: configure_bridges.yml
  loop: "{{ lookup('dict', input_role_bridges_interfaces) }}"
  loop_control:
    loop_var: bridge
  when: 
    - input_role_bridges_interfaces is defined
    - bridge.key != "default"

- name: Configure interface list
  include: configure_list_interface.yml
  loop: "{{ lookup('dict', input_role_list_interfaces) }}"
  loop_control:
    loop_var: interface_list
  when: 
    - input_role_list_interfaces is defined
    - interface_list.key != "default"

- name: Configure VLan interfaces
  include: configure_vlan.yml
  loop: "{{ lookup('dict', input_role_vlan_interfaces) }}"
  loop_control:
    loop_var: vlan
  when: 
    - input_role_vlan_interfaces is defined
    - vlan.key != "default"