---
- name: "[DEBUG] RouterOs Commands"
  debug:
    msg:
      - /interface list print where name={{ interface_list['value']['name'] }}
      - >
        /interface list add
          name={{ interface_list['value']['name'] }}
          comment="{{ interface_list['value']['comment'] | default('') }}"
          {% if interface_list['value']['other_params'] is defined %}{{ interface_list['value']['other_params'] }}{% endif %}
      - >
        /interface list set [find name={{ interface_list['value']['name'] }}]
          name={{ interface_list['value']['name'] }}
          comment="{{ interface_list['value']['comment'] | default('') }}"
          {% if interface_list['value']['other_params'] is defined %}{{ interface_list['value']['other_params'] }}{% endif %}
  when: input_role_debug == true

- name: "Check: {{ interface_list['value']['name'] }} is interface list exist"
  routeros_command:
    commands: /interface list print where name={{ interface_list['value']['name'] }}
  register: interface_list_status

- name: "[DEBUG] Check: {{ interface_list['value']['name'] }} is interface list exist output"
  debug:
    msg: "{{ interface_list_status.stdout_lines }}"
  when: input_role_debug == true

- name: "Add interface list {{ interface_list['value']['name'] }}"
  routeros_command:
    commands: >
      /interface list add
        name={{ interface_list['value']['name'] }}
        comment="{{ interface_list['value']['comment'] | default('') }}"
        {% if interface_list['value']['other_params'] is defined %}{{ interface_list['value']['other_params'] }}{% endif %}
  when: '" 0 " in interface_list_status.stdout_lines[0]'
  register: add_interface_list_status

- name: "[DEBUG] Add interface list {{ interface_list['value']['name'] }} output"
  debug:
    msg: "{{ add_interface_list_status.stdout_lines }}"
  when:
    - input_role_debug == true
    - add_interface_list_status.stdout_lines is defined

- name: "Update interface list {{ interface_list['value']['name'] }}"
  routeros_command:
    commands: >
        /interface list set [find name={{ interface_list['value']['name'] }}]
          name={{ interface_list['value']['name'] }}
          comment="{{ interface_list['value']['comment'] | default('') }}"
          {% if interface_list['value']['other_params'] is defined %}{{ interface_list['value']['other_params'] }}{% endif %}
  when: '" 0 " not in interface_list_status.stdout[0]'
  register: update_interface_list_status

- name: "[DEBUG] Update interface list {{ interface_list['value']['name'] }} output"
  debug:
    msg: "{{ update_interface_list_status.stdout_lines }}"
  when:
    - input_role_debug == true
    - update_interface_list_status.stdout_lines is defined


# Members
- name: Configure members of interface list
  include: configure_list_interface_members.yml
  loop: "{{ interface_list['value']['interfaces'] }}"
  loop_control:
    loop_var: member
  when: interface_list.value.interfaces is defined