---
- name: "[DEBUG] RouterOs Commands"
  debug:
    msg:
      - /interface list member print detail where list={{ interface_list['value']['name'] }} interface={{ member.name }}
      - >
        /interface list member add
          comment="{{ member.comment | default('') }}"
          interface={{ member.name }}
          list={{ interface_list['value']['name'] }}
          disabled={{ member.disabled | default('no')}}
      - >
        /interface list member [find interface={{ member.name }}]
          comment="{{ member.comment | default('') }}"
          list={{ interface_list['value']['name'] }}
          disabled={{ member.disabled | default('no')}}
  when: input_role_debug == true

- name: "Check: {{ member.name }} is exist on {{ interface_list['value']['name'] }} interface list"
  routeros_command:
    commands: /interface list member print detail where list={{ interface_list['value']['name'] }} interface={{ member.name }}
  register: member_list_status

- name: "[DEBUG] Check: {{ member.name }} is exist on {{ interface_list['value']['name'] }} interface list output"
  debug:
    msg: "{{ member_list_status.stdout_lines }}"
  when: input_role_debug == true

- name: "Add {{ member.name }} to {{ interface_list['value']['name'] }} interface list"
  routeros_command:
    commands: >
      /interface list member add
        comment="{{ member.comment | default('') }}"
        interface={{ member.name }}
        list={{ interface_list['value']['name'] }}
        disabled={{ member.disabled | default('no')}}
  when: '" 0 " not in member_list_status.stdout[0]'
  register: add_member_list_status

- name: "[DEBUG] Add {{ member.name }} to {{ interface_list['value']['name'] }} interface list output"
  debug:
    msg: "{{ add_interface_list_status.stdout_lines }}"
  when:
    - input_role_debug == true
    - add_interface_list_status.stdout_lines is defined

- name: "Update {{ member.name }} to {{ interface_list['value']['name'] }} interface list"
  routeros_command:
    commands: >
      /interface list member [find interface={{ member.name }}]
        comment="{{ member.comment | default('') }}"
        list={{ interface_list['value']['name'] }}
        disabled={{ member.disabled | default('no')}}
  when: '" 0 " not in member_list_status.stdout[0]'
  register: update_member_list_status

- name: "[DEBUG] Update {{ member.name }} to {{ interface_list['value']['name'] }} interface list output"
  debug:
    msg: "{{ update_member_list_status.stdout_lines }}"
  when:
    - input_role_debug == true
    - update_member_list_status.stdout_lines is defined