---
- name: "[DEBUG] RouterOs Commands"
  debug:
    msg:
      - /ip address print where address="{{ bridge_interface['value']['address'] }}" interface={{ bridge_interface['value']['name'] }}
      - >
        /ip address add
          address={{ bridge_interface['value']['address'] }}
          network={{ bridge_interface['value']['network'] }}
          interface={{ bridge_interface['value']['name'] }}
          comment="{{ bridge_interface['value']['comment'] | default('') }}"
      - >
        /ip address set [ find address="{{ bridge_interface['value']['address'] }}" ]
          network={{ bridge_interface['value']['network'] }}
          interface={{ bridge_interface['value']['name'] }}
          comment="{{ bridge_interface['value']['comment'] | default('') }}"
  when: input_role_debug == true

- name: "Check is set ip address for {{ bridge_interface['key'] }}"
  routeros_command:
    commands: /ip address print where address="{{ bridge_interface['value']['address'] }}" interface={{ bridge_interface['value']['name'] }}
  register:  bridge_interface_ip_status

- name: "[DEBUG] Check is set ip address for {{ bridge_interface['key']  }} output"
  debug:
    msg: "{{ bridge_interface_ip_status.stdout_lines }}"
  when: input_role_debug == true

- name: "Add ip address for {{ bridge_interface['key']  }} - {{ bridge_interface['value']['address'] }}"
  routeros_command:
    commands: >
      /ip address add
        address={{ bridge_interface['value']['address'] }}
        network={{ bridge_interface['value']['network'] }}
        interface={{ bridge_interface['value']['name'] }}
        comment="{{ bridge_interface['value']['comment'] | default('') }}"
  when:
    - '" 0 " not in bridge_interface_ip_status.stdout[0]'
  register: add_bridge_interface_ip_status

- name: "[DEBUG] Add ip address for {{ bridge_interface['key']  }} - {{ bridge_interface['value']['address'] }} output"
  debug:
    msg: "{{ add_bridge_interface_ip_status.stdout_lines }}"
  when:
    - add_bridge_interface_ip_status.stdout_lines is defined
    - input_role_debug == true

- name: "Update ip address for {{ bridge_interface['key']  }} - {{ bridge_interface['value']['address'] }}"
  routeros_command:
    commands: >
      /ip address set [ find address="{{ bridge_interface['value']['address'] }}" ]
      network={{ bridge_interface['value']['network'] }}
      interface={{ bridge_interface['value']['name'] }}
      comment="{{ bridge_interface['value']['comment'] | default('') }}"
  when:
    - '" 0 " in bridge_interface_ip_status.stdout[0]'
  register: update_bridge_interface_ip_status

- name: "[DEBUG] Update ip address for {{ bridge_interface['key']  }} - {{ bridge_interface['value']['address'] }}"
  debug:
    msg: "{{ update_bridge_interface_ip_status.stdout_lines }}"
  when:
    - update_bridge_interface_ip_status.stdout_lines is defined
    - input_role_debug == true
