---
- name: Configure Router
  hosts: routeros
  tasks:
    - include_role:
        name: Mikrotik-CreateBackup
      vars:
        input_role_destination_path: /volumes/mikrotik
        input_role_ansible_host:     "{{ ansible_host }}"
        input_role_ansible_user:     "{{ ansible_user }}"
        input_role_ansible_password: "{{ ansible_password }}"

    # - include_role:
    #     name: Mikrotik-SetIdentity
    #   vars:
    #     input_role_ansible_host:     "{{ inventory_hostname }}"

    - include_role:
        name: Mikrotik-Interface
      vars:
        input_role_interfaces_bridges:  "{{ inventory_group_routeros_interfaces_bridges }}"
        input_role_interfaces_ethernet: "{{ inventory_group_routeros_interfaces_ethernet }}"
        input_role_interfaces_list:     "{{ inventory_group_routeros_interfaces_list }}"

    # - include_role:
    #     name: Mikrotik-ConfigureDNS
    #   vars:
    #     input_role_dns_parameters:     "{{ inventory_group_routeros_dns }}"
    #     input_role_dns_static_records: "{{ iventory_group_routeros_dns_static_records }}"