---
- name: Configure Router
  hosts: routeros
  tasks:
    - include_role:
        name: Mikrotik-CreateBackup
      vars:
        input_role_destination_path: /volumes/mikrotik
        input_role_ansible_host:     "{{ ansible_host }}"
        input_role_ansible_user:     "{{ ansible_user }}"
        input_role_ansible_password: "{{ ansible_ssh_pass }}"

    - include_role:
        name: Mikrotik-SetIdentity
      vars:
        input_role_ansible_host:     "{{ inventory_hostname }}"

    - include_role:
        name: Mikrotik-Interface
      vars:
        input_role_bridges_interfaces:         "{{ inventory_group_routeros_bridges_interfaces }}"
        input_role_ethernet_interfaces:        "{{ inventory_group_routeros_ethernet_interfaces }}"
        input_role_list_interfaces:            "{{ inventory_group_routeros_list_interfaces }}"
        input_role_vlan_interfaces:            "{{ inventory_group_routeros_vlan_interfaces }}"
        input_role_wireless_interfaces:        "{{ inventory_group_routeros_wireless_interfaces }}"
        input_role_wireless_security_profiles: "{{ inventory_group_routeros_wireless_security_profiles }}"

    - include_role:
        name: Mikrotik-DHCP-Server
      vars:
        input_role_pools:        "{{ inventory_group_routeros_pools }}"
        input_role_dhcp_servers: "{{ inventory_group_routeros_dhcp_servers }}"
        input_role_dhcp_network: "{{ inventory_group_routeros_dhcp_networks }}"

    - include_role:
        name: Mikrotik-DHCP-Client
      vars:
        input_role_dhcp_clients:  "{{ inventory_group_routeros_dhcp_clients }}"

    - include_role:
        name: Mikrotik-DNS-Server
      vars:
        input_role_dns_parameters:     "{{ inventory_group_routeros_dns }}"
        input_role_dns_static_records: "{{ iventory_group_routeros_dns_static_records }}"

    - include_role:
        name: Mikrotik-NTP-Client
      vars:
        input_role_ntp_client:     "{{ inventory_group_routeros_ntp_client }}"

    - include_role:
        name: Mikrotik-SSL-Certificates
      vars:
        input_role_server_certificates:     "{{ inventory_group_routeros_certificates }}"
        input_role_ansible_host:            "{{ ansible_host }}"
        input_role_ansible_user:            "{{ ansible_user }}"
        input_role_ansible_password:        "{{ ansible_ssh_pass }}"

    - include_role:
        name: Mikrotik-Graphing

    - include_role:
        name: Mikrotik-Firewall
      vars:
        input_role_firewall_rules:     "{{ inventory_group_routeros_firewall_rules }}"