---
- name: Download backup
  action: command sshpass -p "{{ input_role_ansible_password }}" sftp {{ input_role_ansible_user }}@{{ input_role_ansible_host }}:{{ var_role_backup_filename }} {{ input_role_destination_path }}/backup

- name: Download configuration
  action: command sshpass -p "{{ input_role_ansible_password }}" sftp {{ input_role_ansible_user }}@{{ input_role_ansible_host }}:{{ var_role_backup_filename_rsc }} {{ input_role_destination_path }}/rsc