- name: "[DEBUG] OS Distribution"
  debug:
    msg: "{{ input_role_os_distribution }}"
  when: input_role_debug == true

- name: "[Ubuntu] Install tools"
  delegate_to: localhost
  apt:
    pkg:
    - sshpass
  when: input_role_os_distribution == "Ubuntu"
  register: install_tools_output

- name: "[DEBUG] [Ubuntu] Install tools output"
  debug:
    msg: "{{ install_tools_output }}"
  when: input_role_debug == true
